version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  web:
    build: .
    command: npm run dev
    env_file: .env
    links:
      - mongodb
    volumes:
      - ./:/app

volumes:
  mongodata: